###########
# site.title

title:    'Chicago Young Government Leaders'
subtitle: ''


nav:
- { title: 'Home',              href: '/' }
- { title: 'Events',             href: '/events/' }
- { title: 'Who We Are',             href: '/whoweare/' }
- { title: 'Get updates',             href: '/getupdates/' }




#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

